# Generated by Django 3.2.7 on 2021-12-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional',
            field=models.TextField(null=True),
        ),
    ]
