# Generated by Django 3.2.7 on 2021-12-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_additional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='counttry',
            new_name='country',
        ),
    ]
