# Generated by Django 3.2.7 on 2021-09-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210923_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='No number', max_length=12),
        ),
    ]
