# Generated by Django 3.2.7 on 2021-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211103_2048'),
        ('users', '0004_user_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='users', to='store.Product'),
        ),
    ]
