# Generated by Django 3.2.7 on 2021-09-02 12:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.SlugField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.SlugField(max_length=60)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.SlugField(max_length=165)),
                ('desc', models.CharField(max_length=250, verbose_name='Short description')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img', models.ImageField(default='default.jpg', upload_to='img/%Y/%m/%d', verbose_name='Image')),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('delivery_date', models.PositiveSmallIntegerField(default=0)),
                ('delivery_from', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('is_sale', models.BooleanField(default=False)),
                ('old_price', models.PositiveIntegerField(blank=True)),
                ('bought', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brand')),
                ('buyby', models.ManyToManyField(to='store.DeliveryForm', verbose_name='Buy by')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
                ('tags', models.ManyToManyField(related_name='products', to='store.Tag')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
