# Generated by Django 3.2.7 on 2021-09-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
