# Generated by Django 3.2.7 on 2021-09-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210903_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
